version: "3"

services:
  celery-task-plugins:
    container_name: celery-task-plugins
    image: celery-task-plugins
    build:
      context: .
      args:
        EXTRAS: "[test]"
    tty: true
    entrypoint: ["bash"] #["pytest", "-sv", "."]
    depends_on:
      - celery-redis
      - rabbitmq
    volumes:
      - .:/celery_task_plugins

  celery-redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq_password
      RABBITMQ_ERLANG_COOKIE: rabbitmq_erlang_cookie
